### ISSUE TITLE
Error while training MNIST

### ISSUE THREAD

**Issue by CyanideBoy** [daa233/generative-inpainting-pytorch#40]
Hey, I got the following error while running the training script on MNIST (with 3 channels - converted to RGB). 
```
torch.Size([16, 128, 4, 4])
torch.Size([1, 9, 3, 3])
2020-06-30 06:07:48,118 ERROR Given transposed=1, weight of size [16, 128, 4, 4], expected input[1, 9, 3, 3] to have 16 channels, but got 9 channels instead
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 173, in main
    raise e
  File "train.py", line 116, in main
    losses, inpainted_result, offset_flow = trainer(x, bboxes, mask, ground_truth, compute_g_loss)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/generative-inpainting-pytorch/trainer.py", line 40, in forward
    x1, x2, offset_flow = self.netG(x, masks)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/generative-inpainting-pytorch/model/networks.py", line 27, in forward
    x_stage2, offset_flow = self.fine_generator(x, x_stage1, mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/generative-inpainting-pytorch/model/networks.py", line 164, in forward
    x, offset_flow = self.contextul_attention(x, x, mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/generative-inpainting-pytorch/model/networks.py", line 328, in forward
    yi = F.conv_transpose2d(yi, wi_center, stride=self.rate, padding=1) / 4.  # (B=1, C=128, H=64, W=64)
RuntimeError: Given transposed=1, weight of size [16, 128, 4, 4], expected input[1, 9, 3, 3] to have 16 channels, but got 9 channels instead
```
I got a similar error in the original tensorflow repo as well. The 2 dimensions printed are a result of print statements I inserted
```
print(wi_center.shape)
print(yi.shape)
```
I am attaching a part of the YAML file as well
```
# data parameters
dataset_name: MNIST
data_with_subfolder: False
train_data_path: training_data/training
val_data_path:
resume:
batch_size: 32
image_shape: [28, 28, 3]
mask_shape: [16, 16]
mask_batch_same: True
max_delta_shape: [12, 12]
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 0.9
random_crop: False
mask_type: hole     # hole | mosaic
mosaic_unit_size: 6
```
When I try to do index an element of Dataset, I get a torch tensor of size [3,28,28] which seems ok (although the channels dimension is last in the yaml file).
Any help would be great!

**Comment by daa233** [comment]
The `image_shape: [28, 28, 3]` is too small for the network. You may specify the image_shape with [256, 256, 3] and then resize the MNIST images.
