### ISSUE TITLE
running on another dataset

### ISSUE THREAD

**Issue by ehfo0888** [DAA233/generative-inpainting-pytorch#70]
Hello, I tried to  run your code for another dataset I got the following error:

`Traceback (most recent call last):
  File "C:\Users\f\Desktop\generative-inpainting-pytorch-master\train.py", line 177, in <module>        
    main()
  File "C:\Users\f\Desktop\generative-inpainting-pytorch-master\train.py", line 26, in main
    config = get_config(args.config)
  File "C:\Users\f\Desktop\generative-inpainting-pytorch-master\utils\tools.py", line 476, in get_config
    return yaml.load(stream)
TypeError: load() missing 1 required positional argument: 'Loader'`

**Comment by tieincred-pixis** [comment]
Hey @ehfo0888 just change yaml.load to yaml.safe_load()
The following link has better explanation for this.
https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col
